package net.jfilesync.jfsmw.app;

import net.jfilesync.jfsmw.core.ui.impl.FxApplication;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App{

    public static void main(String[] args) {
        FxApplication.launch(FxApplication.class,args);
    }

}
