package net.jfilesync.jfsmw.app;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import net.jfilesync.jfsmw.core.bundle.JfsMwAppBundle;
import net.jfilesync.jfsmw.core.ui.common.UiSystem;

import java.util.ServiceLoader;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

  public static void main(String[] args) {

    ServiceLoader<AbstractModule> loader   = ServiceLoader.load(AbstractModule.class);
    Injector                      injector = Guice.createInjector(loader);

    ServiceLoader<JfsMwAppBundle> bundles = ServiceLoader.load(JfsMwAppBundle.class);

    for (final JfsMwAppBundle bundle: bundles) {
      injector.injectMembers(bundle);
      bundle.init();
    }
    for (final JfsMwAppBundle bundle: bundles) {
      bundle.start();
    }

    System.out.println("Starting UI");

    UiSystem uiSystem = injector.getInstance(UiSystem.class);
    uiSystem.start();
    System.out.println("App is up and running");
    uiSystem.waitForShutdown();
    System.out.println("Application will exit now");
  }
}
